"""add jingle to station

Revision ID: 19cee274a11d
Revises: 5bba98102e28
Create Date: 2017-10-09 15:31:01.785981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cee274a11d'
down_revision = '5bba98102e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('station_ices', sa.Column('jingle_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'station_ices', 'music', ['jingle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_ices', type_='foreignkey')
    op.drop_column('station_ices', 'jingle_id')
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
