"""add jingle

Revision ID: 3e2d5fcb5a24
Revises: 5bba98102e28
Create Date: 2017-10-10 16:28:58.110027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2d5fcb5a24'
down_revision = '5bba98102e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_ices', sa.Column('jingle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'station_ices', 'music', ['jingle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station_ices', type_='foreignkey')
    op.drop_column('station_ices', 'jingle_id')
    # ### end Alembic commands ###
