"""add station, music,playlist tables

Revision ID: 5bba98102e28
Revises: b03265e7b28f
Create Date: 2017-10-05 13:50:07.889173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bba98102e28'
down_revision = 'b03265e7b28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_ices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('crossfade', sa.Integer(), nullable=False),
    sa.Column('server_host', sa.VARCHAR(length=200), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('server_rotocol', sa.VARCHAR(length=20), nullable=False),
    sa.Column('server_mountpoint', sa.VARCHAR(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('randomize', sa.Boolean(), nullable=True),
    sa.Column('play_from_hour', sa.Integer(), nullable=False),
    sa.Column('play_to_hour', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station_ices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('playlist_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['music.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'playlist_id', 'order', name='unique_order'),
    sa.UniqueConstraint('song_id', 'playlist_id', name='unique_song_playlist_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_music')
    op.drop_table('playlist')
    op.drop_table('station_ices')
    op.drop_table('music')
    # ### end Alembic commands ###
