"""add metadata url to station

Revision ID: 63c0c0a7af26
Revises: 3e2d5fcb5a24
Create Date: 2017-10-12 16:46:16.564795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c0c0a7af26'
down_revision = '3e2d5fcb5a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('metadata_url', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'metadata_url')
    # ### end Alembic commands ###
