"""add ios and android versions

Revision ID: 710e244b06e6
Revises: 8f2a215bafb4
Create Date: 2017-12-18 12:35:47.503714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710e244b06e6'
down_revision = '8f2a215bafb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general', sa.Column('android_current_version', sa.Float(), nullable=True))
    op.add_column('general', sa.Column('ios_current_version', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general', 'ios_current_version')
    op.drop_column('general', 'android_current_version')
    # ### end Alembic commands ###
