"""add general table

Revision ID: 8f2a215bafb4
Revises: b829cce349a1
Create Date: 2017-11-28 15:26:45.228395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2a215bafb4'
down_revision = 'b829cce349a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_main', sa.VARCHAR(length=30), nullable=False),
    sa.Column('mail_ads', sa.VARCHAR(length=30), nullable=False),
    sa.Column('mail_support', sa.VARCHAR(length=30), nullable=False),
    sa.Column('mail_rotation', sa.VARCHAR(length=30), nullable=False),
    sa.Column('phone_main', sa.VARCHAR(length=15), nullable=True),
    sa.Column('phone_secondary', sa.VARCHAR(length=15), nullable=True),
    sa.Column('skype', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('copyright_holder_text', sa.String(), nullable=False),
    sa.Column('facebook_link', sa.String(), nullable=False),
    sa.Column('instagram_link', sa.String(), nullable=False),
    sa.Column('soundcloud_link', sa.String(), nullable=False),
    sa.Column('youtube_link', sa.String(), nullable=False),
    sa.Column('playmarket_link', sa.String(), nullable=True),
    sa.Column('appstore_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general')
    # ### end Alembic commands ###
