"""add db field stream_url_free_channel

Revision ID: b03265e7b28f
Revises: c7bb19ab4ce8
Create Date: 2017-10-04 13:09:17.929742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03265e7b28f'
down_revision = 'c7bb19ab4ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('stream_url_free_channel', sa.VARCHAR(length=200), nullable=True))
    op.alter_column('station', 'stream_url', name='stream_url_music')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('station', 'stream_url_music', name='stream_url')
    op.drop_column('station', 'stream_url_free_channel')
    # ### end Alembic commands ###
