"""add jingle play after field

Revision ID: b829cce349a1
Revises: ecd30614ea98
Create Date: 2017-10-22 22:06:57.617513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b829cce349a1'
down_revision = 'ecd30614ea98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_ices', sa.Column('play_jingle_after_songs_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_ices', 'play_jingle_after_songs_count')
    # ### end Alembic commands ###
