"""add name to image

Revision ID: c0bfce95c01e
Revises: 137f1f3f9660
Create Date: 2017-09-28 17:09:23.416477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bfce95c01e'
down_revision = '137f1f3f9660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('image', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('image', 'name')
    # ### end Alembic commands ###
