"""add html tags

Revision ID: ecd30614ea98
Revises: 63c0c0a7af26
Create Date: 2017-10-19 22:31:25.613854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd30614ea98'
down_revision = '63c0c0a7af26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('html_tag')
    )
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('html_header')
    # ### end Alembic commands ###
